[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Harrison Kiang <hkiang01@gmail.com>"]

[tool.poetry.dependencies]
fastapi = "~0.68.1"
gunicorn = "~20.1.0"
python = "^3.9"
uvicorn = {extras = ["standard"], version = "^0.15.0"}

[tool.poetry.dev-dependencies]
pre-commit = "~2.14.0"
pytest = "^5.2"
black = "^21.7b0"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core~1.1.8"]
build-backend = "poetry.core.masonry.api"
